# Generated by Django 3.2.7 on 2021-12-08 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jshop_app', '0002_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name': 'Category', 'verbose_name_plural': 'catetories'},
        ),
    ]
